# Usa la imagen oficial de MongoDB
FROM mongo:latest

# Crea un directorio de trabajo dentro del contenedor
WORKDIR /workspace

# (Opcional) Copia un script JS para inicializar la base de datos
# COPY mongo-init.js /docker-entrypoint-initdb.d/

# Puerto expuesto
EXPOSE 27017

# El contenedor usará el comando por defecto de la imagen de MongoDB
